# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  mro.revenue.gov.in:

networks:
  test:
    name: fabric_test

services:

  mro.revenue.gov.in:
    container_name: mro.revenue.gov.in
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=mro.revenue.gov.in
      - CORE_PEER_ADDRESS=mro.revenue.gov.in:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=mro.revenue.gov.in:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=mro.revenue.gov.in:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=mro.revenue.gov.in:11051
      - CORE_PEER_LOCALMSPID=RevenueMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../../organizations/peerOrganizations/revenue.gov.in/peers/mro.revenue.gov.in/msp:/etc/hyperledger/fabric/msp
        - ../../organizations/peerOrganizations/revenue.gov.in/peers/mro.revenue.gov.in/tls:/etc/hyperledger/fabric/tls
        - mro.revenue.gov.in:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - test
