version: '3.7'

volumes: {}

networks:
  test:
    external: true
    name: fabric_test

services:

  # ORG1 Peers
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 8051:7051

  peer2.org1.example.com:
    container_name: peer2.org1.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment: &org1_env
      - CORE_PEER_ID=peer2.org1.example.com
      - CORE_PEER_ADDRESS=peer2.org1.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 22051:9051

  peer3.org1.example.com:
    container_name: peer3.org1.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org1.example.com
      - CORE_PEER_ADDRESS=peer3.org1.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer3.org1.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 10051:10051

  # ORG2 Peers
  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_ADDRESS=peer1.org2.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 21051:11051

  peer2.org2.example.com:
    container_name: peer2.org2.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org2.example.com
      - CORE_PEER_ADDRESS=peer2.org2.example.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org2.example.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org2.example.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 12051:12051

  peer3.org2.example.com:
    container_name: peer3.org2.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org2.example.com
      - CORE_PEER_ADDRESS=peer3.org2.example.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer3.org2.example.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org2.example.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer3.org2.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer3.org2.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/peers/peer3.org2.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 13051:13051

  # ORG3 Peers
  peer1.org3.example.com:
    container_name: peer1.org3.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.example.com
      - CORE_PEER_ADDRESS=peer1.org3.example.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.example.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 14051:14051

  peer2.org3.example.com:
    container_name: peer2.org3.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org3.example.com
      - CORE_PEER_ADDRESS=peer2.org3.example.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org3.example.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org3.example.com:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer2.org3.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer2.org3.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer2.org3.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 15051:15051

  peer3.org3.example.com:
    container_name: peer3.org3.example.com
    extends:
      file: docker-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org3.example.com
      - CORE_PEER_ADDRESS=peer3.org3.example.com:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer3.org3.example.com:16052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:16052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org3.example.com:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:11051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric/peer
    volumes:
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer3.org3.example.com/msp:/etc/hyperledger/fabric/peer/msp
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer3.org3.example.com/tls:/etc/hyperledger/fabric/peer/tls
      - /home/kishorenandhan/go/src/github.com/KISHORE-NANDHAN/fabric-samples/test-network/organizations/peerOrganizations/org3.example.com/peers/peer3.org3.example.com/core.yaml:/etc/hyperledger/fabric/peer/core.yaml
    ports:
      - 16051:16051